### ISSUE TITLE
Doesn't run on py 3.8.5 and pytorch 1.8.1

### ISSUE THREAD

**Issue by kma-code** [afkungl/pseudoBackprop#40]
The current version doesn't run on my machine. Running any of the examples or experiments gives the following error:

  File "/Users/km/Software/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/Users/km/Software/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 831, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/140389232768576

The last steps of the traceback are always the same, whether I run experiments/train_mnist.py or single_shut/run_complete.py.

I attach the log generated by single_shot/run_complete.py for the bp run:

[log_train_bp.log](https://github.com/afkungl/pseudoBackprop/files/6262944/log_train_bp.log)

**Comment by kma-code** [comment]
This occurs under torch 1.8.1 installed via pip as well as conda.

**Comment by afkungl** [comment]
I was not able to reproduce the problem.

I used:
python 3.8.0
and installed the pytorch with the website call:
pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

Quick googling tells me that the MNIST you added manually is broken
[here](https://stackoverflow.com/questions/64206070/pytorch-runtimeerror-enforce-fail-at-inline-container-cc209-file-not-fou)
[here](https://github.com/pytorch/pytorch/issues/16741)

It was not able to download the MNIST dataset from the Lecunn site but it changed to an amazon AWS site and got it anyway:
[getting_MNIST.txt](https://github.com/afkungl/pseudoBackprop/files/6267517/getting_MNIST.txt)

Can you look into what exactly happens when it tries to download the MNIST on its own? Does it try to find the amazon aws website?

**Comment by kma-code** [comment]
Indeed, my copy of the MNIST file was broken.
